StepUpper/stepup_front

- frontend/src/components/common/BottomButton.tsx
- frontend/src/components/common/Input.tsx
- frontend/src/components/common/OptionSelectorButton.tsx
- frontend/src/components/common/html/Button.tsx
커스텀 버튼 컴포넌트 생성 완료
> 커스텀 버튼 컴포넌트 생성 완료
Close #8
> Resolves: 커스텀 버튼 컴포넌트 생성 #8

- frontend/src/apis/firebase/chatFirestore.ts
- frontend/src/components/Chat/ChatBrandCard.tsx
- frontend/src/components/Chat/ChatInput.tsx
- frontend/src/components/Chat/ChatRecommendedQuestion.tsx
- frontend/src/pages/Chat/Chat.tsx
- frontend/src/store/useChatStore.ts
- frontend/src/styles/tailwind.css
> 로그인 여부에 따른 처리
<br/><br/>
> 로그인 여부에 따른 처리
> 임시로 로그인 상태와 userid를 지정해놓고 진행하였음
<br/><br/>
#42
> 로그인 여부에 따른 처리

- frontend/eslint.config.js
- frontend/index.html
- frontend/src/components/common/Header.tsx
- frontend/src/components/myFootInfo/FootInfoDisplay.tsx
- frontend/src/pages/MyFootInfo/MyFootInfo.tsx
- frontend/src/router/index.tsx
> 내 발 측정하기 sdk 연결 및 페이지 라우터 처리와 뒤로가기 기능 추가
<br/><br/>
- eslint 규칙 사용되지 않는 변수가 있는 경우 경고로 변경
- 내 발 측정하기 sdk 연결 및 페이지 라우터 처리
- Header 뒤로가기 기능 추가
<br/><br/>
<br/><br/>
> 내 발 측정하기 sdk 연결 및 페이지 라우터 처리

- frontend/src/apis/firebase/auth.ts
- frontend/src/components/Chat/ChatLogin.tsx
- frontend/src/components/common/OptionSelectorButton.tsx
- frontend/src/components/layout/Layout.tsx
- frontend/src/components/login/Login.tsx
- frontend/src/components/login/LoginBottomSheet.tsx
- frontend/src/components/signup/SignUp.tsx
- frontend/src/components/signup/SignUpAdditional.tsx
- frontend/src/components/signup/SignUpRequired.tsx
- frontend/src/firebase.ts
- frontend/src/pages/Chat/Chat.tsx
- frontend/src/router/index.tsx
- frontend/src/router/loaders/onBoading.ts
- frontend/src/store/auth.store.ts
- frontend/src/types/auth.d.ts
> auth 기능 추가
> chrome 서드파티 관련 cors 에러 발생 -> google 로그인 보류
> bottom sheet ui design 수정 보류
<br/><br/>
> firebase-authentication을 통한 로그인, 회원가입, 로그아웃 함수 생성
> firestore DB, user collection 생성
> zustand 전역 user 상태 관리를 위한 userStore 생성
<br/><br/>
#35 
<br/><br/>
> Feat: auth 기능 추가 #35

- frontend/src/components/Chat/ChatMessage.tsx
- frontend/src/store/productAndBrand.store.ts
> 클릭된 brand, products 전역으로 관리
<br/><br/>
#45
> feat : 클릭된 brand, products 전역으로 관리 #45

- frontend/src/apis/firebase/chatFirestore.ts
- frontend/src/assets/assets.ts
- frontend/src/assets/icons/interest-check-icon.svg
- frontend/src/components/Chat/ChatBrandCard.tsx
- frontend/src/components/Chat/ChatInput.tsx
- frontend/src/components/Chat/ChatMessage.tsx
- frontend/src/components/Chat/ChatProductItem.tsx
- frontend/src/components/Chat/ChatRecommendedQuestion.tsx
- frontend/src/components/Chat/InterestKeywordsBottomSheet.tsx
- frontend/src/components/common/ProductLearnMoreButton.tsx
- frontend/src/components/layout/Layout.tsx
- frontend/src/components/login/Login.tsx
- frontend/src/components/myshopping/LikedBrands.tsx
- frontend/src/components/myshopping/LikedItems.tsx
- frontend/src/components/plp/GenderCategorySelector.tsx
- frontend/src/components/sidemenu/SideMenu.tsx
- frontend/src/components/signup/SignUpAdditional.tsx
- frontend/src/pages/Bridge/Bridge.tsx
- frontend/src/pages/Chat/Chat.tsx
- frontend/src/pages/MyPage/MyPage.tsx
- frontend/src/pages/MyShopping/MyShopping.tsx
> 회원가입 후 처리
<br/><br/>
Layout 컴포넌트에서 로그인 여부를 파악하는 로직 재구성
로그인 된 회원 추천질문 눌렀음에도 새로고침하면 다시 뜨는거 해결
chatFirestore 파일에서 addMessageToFirestore 함수의 네번째 인자로 들어가는 bot 메세지의 type 명확하게 설정
키워드 설정 후 선택완료 눌렀을 시 그에 따른 처리
#60
> Feat: 회원가입 후 처리

- frontend/src/components/Chat/ChatBrandCard.tsx
- frontend/src/components/Chat/ChatLogin.tsx
- frontend/src/components/Chat/ChatMessage.tsx
- frontend/src/components/Chat/ChatReqProdItem.tsx
- frontend/src/components/Chat/InterestKeywordsBottomSheet.tsx
- frontend/src/components/common/OptionSelectorButton.tsx
- frontend/src/components/login/Login.tsx
- frontend/src/components/signup/SignUpAdditional.tsx
- frontend/src/types/chat.d.ts
> 로그인 시 맞춤상품 추천, 회원가입 시 관심키워드 설정 및 응답 호출
<br/><br/>
#61
> Feat: 로그인 시 맞춤상품 추천, 회원가입 시 관심키워드 설정 및 응답 호출

- frontend/src/components/shoeCloset/ProfileCard.tsx
- frontend/src/components/sidemenu/SideMenu.tsx
- frontend/src/pages/MyPage/MyPage.tsx
- frontend/src/router/index.tsx
> 사이드메뉴, 마이페이지, 신발장 화면에서 유저 정보 가져와서 정보 출력되도록 변경
<br/><br/>
> 하단 이름
> 내 정보(이름, 성별, 생년월일, 평소 사이즈)
> 성별은 genderLabel 통해서 남성, 여성으로 표시되도록 변환
<br/><br/>
#32 #27
<br/><br/>
> 로그인된 유저 정보 받아와서 출력

- frontend/src/components/signup/SignUpAdditional.tsx
> signup additional에서 입력한 값 db에 저장
<br/><br/>
#68
> feat: signup additional에서 입력한 값 db에 저장#68

- frontend/src/components/Chat/ChatMessage.tsx
> 중간발표 전 markdown 디자인 수정
<br/><br/>
#71
> feat: 중간발표 전 markdown 디자인 수정

- frontend/src/components/common/Error.tsx
- frontend/src/components/common/ProductLearnMoreButton.tsx
- frontend/src/components/login/LoginBottomSheet.tsx
- frontend/src/components/myshopping/LikedItems.tsx
- frontend/src/components/plp/BrandPLP.tsx
- frontend/src/components/plp/FilterBottomSheet.tsx
- frontend/src/components/plp/PLPBottomSheet.tsx
- frontend/src/components/plp/PLPProductDisplay.tsx
- frontend/src/components/plp/ProductsPLP.tsx
- frontend/src/components/shoeCloset/register/ReviewOptionSelectorButton.tsx
- frontend/src/components/shoeCloset/register/SearchShoeButton.tsx
- frontend/src/components/shoeCloset/register/ShoeRegisterInputForm.tsx
- frontend/src/components/shoeCloset/register/SubmitBottomButton.tsx
- frontend/src/components/sidemenu/SideChatListItem.tsx
- frontend/src/components/sidemenu/SideMenu.tsx
- frontend/src/hooks/useAxios.ts
- frontend/src/pages/MyFootInfo/MyFootInfo.tsx
- frontend/tsconfig.paths.json
> build type 에러 해결와 사용하지 않는 변수, 함수명 제거 및 주석 처리
<br/><br/>
<br/><br/>
> fix: build 에러 해결

- frontend/src/assets/assets.ts
- frontend/src/components/sidemenu/SideMenu.tsx
> fix: 사이드메뉴 타입에러 해결
<br/><br/>
- 날짜 비교할때 timestamp, createdAt 에서 타입에러 발생
- (기존) timestamp를 Date 형태로 변환 후 비교
- (변경) 변환 없이 today를 timestamp로 받아와서 비교
<br/><br/>
#85 
<br/><br/>
> 사이드메뉴 타입에러 해결

- frontend/src/apis/firebase/chatFirestore.ts
- frontend/src/apis/firebase/likeFirestore.ts
- frontend/src/components/Chat/ChatMessage.tsx
- frontend/src/components/Chat/ChatProductItem.tsx
- frontend/src/components/Chat/ChatShareDislikeBox.tsx
- frontend/src/components/Chat/ChatShareModal.tsx
- frontend/src/components/Chat/ChatShareView.tsx
- frontend/src/components/login/Login.tsx
- frontend/src/router/index.tsx
- frontend/src/store/auth.store.ts
- frontend/src/store/chat.store.ts
> 공유하기
<br/><br/>
> 공유하기
<br/><br/>
#81
> feat: 공유하기

- frontend/src/apis/firebase/chatFirestore.ts
- frontend/src/apis/firebase/likeFirestore.ts
- frontend/src/components/Chat/ChatMessage.tsx
- frontend/src/components/Chat/ChatShareModal.tsx
- frontend/src/components/Chat/ChatShareView.tsx
- frontend/src/components/sidemenu/SideChatListItem.tsx
- frontend/src/components/sidemenu/SideMenu.tsx
- frontend/src/pages/Chat/Chat.tsx
- frontend/src/store/chat.store.ts
> 공유하기 마무리, 채팅방 개설
<br/><br/>
#94
> feat: 공유하기 마무리, 채팅방 개설

- frontend/src/apis/firebase/likeFirestore.ts
- frontend/src/components/Chat/ChatMessage.tsx
- frontend/src/components/Chat/ChatProductItem.tsx
- frontend/src/components/common/ProductList.tsx
- frontend/src/components/myshopping/LikedItems.tsx
- frontend/src/store/auth.store.ts
- frontend/src/utils/storeRecentProducts.ts
> 상품 데이터 값 통일 작업
<br/><br/>
#99 
<br/><br/>
> feat : 상품 데이터 값 통일 작업

- frontend/src/components/Chat/ChatMessage.tsx
- frontend/src/components/myshopping/LikedProducts.tsx
- frontend/src/components/sidemenu/SideMenu.tsx
> markdown 디자인 수정, 새채팅 누르면 채팅기록 초기화
#104
> feat: markdown 디자인 수정, 새채팅 누르면 채팅기록 초기화

- frontend/src/apis/firebase/chatFirestore.ts
- frontend/src/components/sidemenu/SideMenu.tsx
> 채팅방 삭제, 현재 속한 채팅방 표시
<br/><br/>
> chatFirestore에 채팅방 삭제 함수 추가
> 채팅방 삭제(채팅방 삭제 시 현재 속한 채팅방일 경우 채팅 기록들을 가장 최신 채팅으로 업데이트)
> 현재 속한 채팅방 표시
<br/><br/>
#107
> feat : 채팅방 삭제, 현재 속한 채팅방 표시 #107

- frontend/src/apis/firebase/chatFirestore.ts
- frontend/src/components/sidemenu/SideMenu.tsx
> 채팅방 삭제, 현재 속한 채팅방 표시
<br/><br/>
> 채팅방 삭제, 현재 속한 채팅방 표시
#107
<br/><br/>
<br/><br/>
> 채팅방 삭제, 현재 속한 채팅방 표시

- frontend/src/apis/firebase/auth.ts
- frontend/src/apis/firebase/closetFirestore.ts
- frontend/src/store/auth.store.ts
> 신발장 신발 등록 및 업데이트 함수 구현
<br/><br/>
#122 
<br/><br/>
> feat: 신발장 신발 등록 및 업데이트 함수 구현 #122

- frontend/src/components/myshopping/LikedProducts.tsx
- frontend/src/components/myshopping/RecentProducts.tsx
- frontend/src/components/shoeCloset/AddShoeButton.tsx
- frontend/src/components/shoeCloset/EmptyShoeCard.tsx
- frontend/src/components/shoeCloset/EmptyShoeComponent.tsx
- frontend/src/components/shoeCloset/ShoeComponent.tsx
- frontend/src/components/shoeCloset/register/RatingComponent.tsx
- frontend/src/components/shoeCloset/register/RecomendSizeRadioGroup.tsx
- frontend/src/components/shoeCloset/register/SearchShoeButton.tsx
- frontend/src/components/sidemenu/SideMenu.tsx
- frontend/src/pages/MyPage/MyPage.tsx
- frontend/src/pages/MyShopping/MyShopping.tsx
- frontend/src/pages/ShoeCloset/SearchShoeCloset.tsx
- frontend/src/pages/ShoeCloset/ShoeCloset.tsx
- frontend/src/pages/ShoeCloset/ShoeClosetAdd.tsx
- frontend/src/pages/ShoeCloset/ShoeClosetDetail.tsx
- frontend/src/pages/ShoeCloset/ShoeClosetModify.tsx
- frontend/src/router/index.tsx
> 신발장 컴포넌트, 페이지 폴더 수정
> 신발장 관련 페이지 router path 수정
> 기타 css 수정
<br/><br/>
> 신발장 관련 컴포넌트 구분하기 쉽게 이름 통일하여 수정
> 신발장 페이지 컴포넌트 명 ShoeCloset ~~~ 로 변경
> review 폴더 삭제하고 안에 있는 페이지 바깥으로 빼기
>> ShoeClosetOverview -> ShoeClosetDetail
>>Review ->  ShoeClosetAdd
>> Modify -> ShoeClosetModify
> path명 : shoecloset
> path명 : shoecloset/add
> 등
> 빈 신발장 페이지 바텀버튼 화면 깨짐 이슈 수정
> 신발 검색 페이지 바텀버튼 화면 깨짐 이슈 수정
> 신발장 리스트 컴포넌트 cursor pointer 적용
> 신발 등록 페이지 rating 영역, 사이즈 추천 영역 cursor pointer 적용
<br/><br/>
<br/><br/>
> 신발장 컴포넌트, 페이지 네이밍, Router path 변경 및 기타 css 수정

- frontend/src/apis/firebase/auth.ts
- frontend/src/components/Chat/ChatLogin.tsx
> 구글 로그인 기능 연결
<br/><br/>
> 구글 로그인 연결
<br/><br/>
#50 
<br/><br/>
> feat: Add Google Login #50

- frontend/src/components/shoeCloset/search/ImageSearch/ShoeImageSearchResult.tsx
- frontend/src/components/shoeCloset/search/ImageSearch/SimilarShoeList.tsx
> 비슷한 상품 더보기에서 선택된 상품 등록되도록 수정
<br/><br/>
> 하하하.. dev에서 테스트 해보니 계속 첫번째 상품만 등록되었습니다.. 살펴보니 부모 selectedResult state에 선택된 상품 저장해줘야하는데 잘 못 저장되고 있더라고요 ㅠㅠ  수정했습니다 ㅠㅠ
<br/><br/>
#151
<br/><br/>
> 비슷한 상품 더보기에서 선택된 상품 등록되도록 수정

- frontend/src/components/Chat/ChatLoading.tsx
- frontend/src/components/layout/Layout.tsx
- frontend/src/pages/Chat/Chat.tsx
- frontend/src/types/chat.d.ts
> 무한스크롤, 로딩 중 표시(깜빡임 제거)
<br/><br/>
> (로그인 된 회원의 경우) 스크롤 최상단으로 올릴때마다 이전 메세지 5개씩 추가 로드
> 인증 상태를 확인하는 중임을 나타내는 isAuthLoading라는 상태를 만들어서 (인증 상태)확인 중이면 로딩UI 가 나타나게끔
<br/><br/>
#161 #160 #156 
<br/><br/>
> 무한스크롤, 로딩 중 표시

- frontend/vite.config.ts
> 배포 환경에서 console.log가 그대로 남아 있어 불필요한 디버깅 로그가 노출되는 문제를 해결하기 위해 Vite 설정에 console.log를 제거하는 기능을 추가했습니다. 개발 환경에서는 로그를 유지하고, 배포 환경에서는 자동으로 console.log가 제거되도록 설정하였습니다.
<br/><br/>
> vite.config.ts 파일에서 esbuild의 pure 옵션을 사용하여 배포 환경에서만 console.log를 제거하도록 수정
> 테스트 방법은 아래를 참고해주세요.
- 개발 환경: `npm run dev`
- 배포 환경: `npm run build` 후 `npm run preview`
<br/><br/>
#165
<br/><br/>
> vite.congif.ts에 배포 시 console.log 및 debugger 자동 제거 설정 추가 
